/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentRecord extends org.jooq.impl.UpdatableRecordImpl<tech.codingclub.helix.tables.records.StudentRecord> implements org.jooq.Record9<java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 506409404;

	/**
	 * Setter for <code>public.student.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.student.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.student.rollNo</code>.
	 */
	public void setRollno(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.student.rollNo</code>.
	 */
	public java.lang.String getRollno() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.student.email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.student.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.student.dob</code>.
	 */
	public void setDob(java.sql.Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.student.dob</code>.
	 */
	public java.sql.Date getDob() {
		return (java.sql.Date) getValue(3);
	}

	/**
	 * Setter for <code>public.student.mobno</code>.
	 */
	public void setMobno(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.student.mobno</code>.
	 */
	public java.lang.Long getMobno() {
		return (java.lang.Long) getValue(4);
	}

	/**
	 * Setter for <code>public.student.gender</code>.
	 */
	public void setGender(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.student.gender</code>.
	 */
	public java.lang.String getGender() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.student.branch</code>.
	 */
	public void setBranch(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.student.branch</code>.
	 */
	public java.lang.String getBranch() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>public.student.hobbies</code>.
	 */
	public void setHobbies(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.student.hobbies</code>.
	 */
	public java.lang.String getHobbies() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>public.student.password</code>.
	 */
	public void setPassword(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.student.password</code>.
	 */
	public java.lang.String getPassword() {
		return (java.lang.String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.String, java.lang.Long> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return tech.codingclub.helix.tables.Student.STUDENT.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return tech.codingclub.helix.tables.Student.STUDENT.ROLLNO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return tech.codingclub.helix.tables.Student.STUDENT.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field4() {
		return tech.codingclub.helix.tables.Student.STUDENT.DOB;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field5() {
		return tech.codingclub.helix.tables.Student.STUDENT.MOBNO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return tech.codingclub.helix.tables.Student.STUDENT.GENDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return tech.codingclub.helix.tables.Student.STUDENT.BRANCH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return tech.codingclub.helix.tables.Student.STUDENT.HOBBIES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return tech.codingclub.helix.tables.Student.STUDENT.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getRollno();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value4() {
		return getDob();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value5() {
		return getMobno();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getGender();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getBranch();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getHobbies();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value1(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value2(java.lang.String value) {
		setRollno(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value3(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value4(java.sql.Date value) {
		setDob(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value5(java.lang.Long value) {
		setMobno(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value6(java.lang.String value) {
		setGender(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value7(java.lang.String value) {
		setBranch(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value8(java.lang.String value) {
		setHobbies(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord value9(java.lang.String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StudentRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.sql.Date value4, java.lang.Long value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StudentRecord
	 */
	public StudentRecord() {
		super(tech.codingclub.helix.tables.Student.STUDENT);
	}

	/**
	 * Create a detached, initialised StudentRecord
	 */
	public StudentRecord(java.lang.String name, java.lang.String rollno, java.lang.String email, java.sql.Date dob, java.lang.Long mobno, java.lang.String gender, java.lang.String branch, java.lang.String hobbies, java.lang.String password) {
		super(tech.codingclub.helix.tables.Student.STUDENT);

		setValue(0, name);
		setValue(1, rollno);
		setValue(2, email);
		setValue(3, dob);
		setValue(4, mobno);
		setValue(5, gender);
		setValue(6, branch);
		setValue(7, hobbies);
		setValue(8, password);
	}
}
