/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Student extends org.jooq.impl.TableImpl<tech.codingclub.helix.tables.records.StudentRecord> {

	private static final long serialVersionUID = -2100895554;

	/**
	 * The singleton instance of <code>public.student</code>
	 */
	public static final tech.codingclub.helix.tables.Student STUDENT = new tech.codingclub.helix.tables.Student();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<tech.codingclub.helix.tables.records.StudentRecord> getRecordType() {
		return tech.codingclub.helix.tables.records.StudentRecord.class;
	}

	/**
	 * The column <code>public.student.name</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.StudentRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>public.student.rollNo</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.StudentRecord, java.lang.String> ROLLNO = createField("rollNo", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.student.email</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.StudentRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>public.student.dob</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.StudentRecord, java.sql.Date> DOB = createField("dob", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>public.student.mobno</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.StudentRecord, java.lang.Long> MOBNO = createField("mobno", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>public.student.gender</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.StudentRecord, java.lang.String> GENDER = createField("gender", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.student.branch</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.StudentRecord, java.lang.String> BRANCH = createField("branch", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>public.student.hobbies</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.StudentRecord, java.lang.String> HOBBIES = createField("hobbies", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>public.student.password</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.StudentRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * Create a <code>public.student</code> table reference
	 */
	public Student() {
		this("student", null);
	}

	/**
	 * Create an aliased <code>public.student</code> table reference
	 */
	public Student(java.lang.String alias) {
		this(alias, tech.codingclub.helix.tables.Student.STUDENT);
	}

	private Student(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.StudentRecord> aliased) {
		this(alias, aliased, null);
	}

	private Student(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.StudentRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, tech.codingclub.helix.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<tech.codingclub.helix.tables.records.StudentRecord> getPrimaryKey() {
		return tech.codingclub.helix.Keys.STUDENT_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<tech.codingclub.helix.tables.records.StudentRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<tech.codingclub.helix.tables.records.StudentRecord>>asList(tech.codingclub.helix.Keys.STUDENT_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public tech.codingclub.helix.tables.Student as(java.lang.String alias) {
		return new tech.codingclub.helix.tables.Student(alias, this);
	}

	/**
	 * Rename this table
	 */
	public tech.codingclub.helix.tables.Student rename(java.lang.String name) {
		return new tech.codingclub.helix.tables.Student(name, null);
	}
}
